version: '3.8'
services:
# GRAFANA
  grafana:
    image: grafana/grafana:7.4.2
    container_name: grafana
    volumes:
      - ./conf/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: root # Usuario de la web
      GF_SECURITY_ADMIN_PASSWORD: root # Pass de la web
      GF_INSTALL_PLUGINS: percona-percona-app # Instalar el plugin de prometheus
      
      
  # PROMETHEUS
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./conf/prometheus/prometheus.yml:/prometheus/prometheus.yml
    command: 
      - --config.file=/prometheus/prometheus.yml # Especificamos el archivo de configuracion
    ports:
      - "9090:9090"
      
      
