# ESTE ARCHIVO ES LA CONFIGURACION DEL GRAFANA, PARA NO TENER QUE ENTRAR Y PONERLO LOS DATOS DE LOKI Y PROMETHEUS
apiVersion: 1

deleteDatasources:
  - name: Prometheus

# DE DONDE COGE LOS DATOS
datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
