global:
  scrape_interval: 5s 
  evaluation_interval: 5s

scrape_configs:
# PARA MONITORIZAR PROMETEUS
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'snmp'
    static_configs:
      - targets:
        - "10.36.0.13"
    metrics_path: "/snmp"
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9116  # The SNMP exporter's real hostname:port.

